name: Ecoweave - creativity with crisp packets 
markdown: redcarpet
pygments: true
author: ecoweave.co.uk
title: Ecoweave
description: Upcycling discarded crisp packets to create wonderfully functional products
keywords:
- crisp packet bag
- crisp packet
- upcycle
- candy wrapper
- crisp packet products