- id: medium-handbag
  paypal-id: SVDCH84KSYH2Y
  options:
   - Barcode: £65
  colors: []
  name: Medium Handbag
  price: £35
  size: Bag 28.5cm x 19.5cm x 8cm, Handles 39cm
  closure: Zip
  img: medium-handbag-multi.jpg
  category: [handbags, highlight]
  strapline: Stylish and practical
  preamble: |
    This medium size handbag has a secure zip closure and is perfect for everyday use. Large enough for all of your essentials and stylish enough to take anywhere. A high quality zip ensures that all of your belongings are kept safe and out of sight.
  description: |
    Shown here in the traditional multicoloured style which offers the maximum variety for impromptu 'name the packet' sessions. Made from approximately 115 crisp packets it takes four to five days to create. If you would like a particular colour or theme just let me know, I'll be happy to hear what you have in mind.

- id: large-clutch-bag
  paypal-id: WSQVCMAT3656S
  options:
   - Standard: £30
   - Barcode: £55
  colors: [Multicoloured]
  name: Large Clutch Bag
  price: £30
  size: 29.5cm x 16cm x 8cm
  closure: Magnetic
  img: new/large-clutch-multi.jpg
  category: [handbags]
  strapline: Eye-catchingly elegant
  preamble : | 
    This bag is handcrafted from over 100 crisp packets and finished with a quality magnetic clasp. Seen here in the popular multicolour style but, as with all the products, available in any style you'd like.
  description: 

- id: small-clutch-bag
  paypal-id: RFEFJH5QFDZA2
  options:
   - Standard: £25
   - Barcode: £45
  colors: [Blue, Pastel Multicoloured, Silver & Red]
  name: Small Clutch Bag
  price: £25
  size: 24cm x 13.5cm x 4.5cm
  closure: Zip
  img: small-clutch-silver-black-front.jpg
  category: [handbags]
  strapline: Perfectly formed
  preamble: | 
    This small clutch is big enough to carry a purse, phone and a couple of other essentials while still being small enough to not get in your way. If you would like a particular colour or style please get in touch and I'll be happy to discuss options.  
  description:

- id: small-purse
  paypal-id: Q338LW728BFGA
  options:
   - Standard: £10
   - Barcode: £18
  colors: [Multicoloured, Blue, Gold, Green, Pastel Multicoloured, Red, Silver, Black & Red]
  name: Small Purse
  price: £10
  size: 12cm x 9cm x 2.5cm§
  closure: Zip
  img: purse-multi.jpg
  category: [purses]
  strapline: Fill it with your money
  preamble: | 
    These fun purses make great gifts. Made from over 16 packets, the standard size is large enough for coins, notes, and a couple of cards but small enough to fit in a pocket. 
  description: |
        If you would like larger or smaller size then I am happy to make the necessary adjustments. The purses are totally secure, so you need not worry about your stuff dropping out.

- id: wash-bag
  paypal-id: DB6KG3E4QSSJL
  options:
   - Standard: £25
  colors: [Multicoloured, Silver]
  name: Wash / Makeup Bag
  price: £25
  size: Bag 23cm x 14cm x 9cm
  closure: Zip
  img: new/wash-bag.jpg
  category: [gifts]
  strapline: Perfect at home or away
  preamble: |
    This versatile bag is perfect for use as a makeup or wash bag. It has a high quality zip closure and a wide opening for easy access.
  description: |
    It is shown here in the popular multicoloured style. If you have ideas for particular colours or themes just let me know, I'm always keen to hear suggestions.

- id: bookmark
  paypal-id: 6FLYMW8D575WC
  options:
   - Standard: £6
   - Barcode: £10
  colors: [Multicoloured, Blue]
  name: Bookmark
  price: £6
  size: 16cm x 5cm
  closure:
  img: new/bookmark-multi.jpg
  category: [gifts]
  strapline: For the bookworms
  preamble: |
    E-book readers are great, as are our Kindle covers, but sometimes it's nice to leave technology behind and drift away with a book in the good old paper format. Each bookmark is available in any colour and comes complete with a sturdy eyelet and ribbon.
  description:

- id: pencil-case
  paypal-id: BGMMH2RN2VZ2J
  options:
   - Standard: £11
  colors: [Blue, Pink, Red, Silver]
  name: Pencil Case
  price: £11
  size: 24cm x 10.5cm x 4.5cm
  closure: Zip
  img: pencil-case-blue.jpg
  category: [gifts, highlight]
  strapline: A gift for the gifted
  preamble: |
     These pencil cases are quickly becoming the talk of classrooms all over. Made with quality zip closures they will withstand many years of use.
  description:

- id: glasses-case
  paypal-id: HRLN4WE5SFQUC
  options:
   - Standard: £8
   - Barcode: £14
  colors: [Multicoloured, Blue, Green, Black, Pink, Silver, Silver & Purple]
  name: Glasses Case
  price: £8
  size: 16.5cm x 7cm x 2.5cm
  closure: 
  img: glasses-case-multi.jpg
  category: [accessories]
  strapline: Protect your specs
  preamble: |
        A very popular item, these glasses cases protect your glasses from day to day knocks and scrapes and bring a bit of pizazz to an otherwise mundane object. 
  description: |
        The standard size has been tested on a wide range of glasses to provide a sung fit. If your glasses are larger or more flamboyant than most then include the size when you get in touch. The cases can be made in any design and colour and all come with a free cleaning cloth.

- id: keyring
  paypal-id: 7996EYEQUZ6EC
  options:
   - Standard: £6
   - Barcode: £10
  colors: [Multicoloured, Silver, Pastel Multicoloured, Pink & Silver]
  name: Keyring
  price: £6
  size: 3.5cm x 3.5cm x 3.5cm, keychain & ring 6cm
  closure: 
  img: new/keyring-purple-silver.jpg
  category: [gifts]
  strapline:  Make keys hard to lose
  preamble: | 
        Made using quality hardware and filled with polystyrene to maintain their shape these keyrings are a great way to keep track of your keys. 
  description: |
        Made from 5 individual crisp packets these are great conversation pieces. Their light weight and bold design makes them remarkably effective keyrings.

- id: placemats-coasters
  paypal-id: 4PAS98FGC9DXN
  options:
   - 4 Placemats: £20
   - 4 Coasters: £10
  colors: [Silver]
  name: Placemats & Coasters
  price: 4 placemats £20, 4 coasters £10
  size: Placemats 24.5cm x 23cm x 0.5cm, Coasters 12.5cm x 10.5cm x 0.5cm
  closure: 
  img: new/placemat-coaster-multi.jpg
  category: [household]
  strapline: Striking and practical
  preamble: | 
        These placemats and coasters provide a quality cushioned feel and offer excellent protection against the heat of a plate or cup. Spills can be easily wiped clean with a damp cloth.
  description: |
         Each placemat is made from over 80 crisp packets and is large enough for a large dinner plate. The coasters are made from 6 packets and are suitable for most cups or large mugs. As with all of my products I am happy to adjust colours and sizes to suite your needs.
